export const programs = [
  {
    id: 1,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "4 week",
    date: "May 21 - June 15",
    enrolled: 0,
  },
  {
    id: 2,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "4 week",
    date: "June 18 - July 13",
    enrolled: 0,
  },
  {
    id: 3,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "4 week",
    date: "July 16 - August 10",
    enrolled: 0,
  },
  {
    id: 4,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "4 week",
    date: "July 30 - August 24",
    enrolled: 0,
  },
  {
    id: 5,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "May 21 - June 1",
    enrolled: 0,
  },
  {
    id: 6,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "June 4 - June 15",
    enrolled: 0,
  },
  {
    id: 7,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "June 18 - June 29",
    enrolled: 0,
  },
  {
    id: 8,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 2 - July 13",
    enrolled: 0,
  },
  {
    id: 9,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 16 - July 27",
    enrolled: 0,
  },
  {
    id: 10,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 30 - August 10",
    enrolled: 0,
  },
  {
    id: 11,
    value: "youthEmpowerment",
    type: "Youth Empowerment",
    length: "2 week",
    date: "August 13 - August 24",
    enrolled: 0,
  },
  {
    id: 12,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "May 21 - June 1",
    enrolled: 0,
  },
  {
    id: 13,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "June 4 - June 15",
    enrolled: 0,
  },
  {
    id: 14,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "June 18 - June 29",
    enrolled: 0,
  },
  {
    id: 15,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "July 2 - July 13",
    enrolled: 0,
  },
  {
    id: 16,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "July 16 - July 27",
    enrolled: 0,
  },
  {
    id: 17,
    value: "healthInnovation",
    type: "Health Innovation",
    length: "2 week",
    date: "July 30 - August 10",
    enrolled: 0,
  }
];